kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-data
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  local:
    path: /kubernetes-persistent-volume/mongodb
  persistentVolumeReclaimPolicy: Retain
  {{- range .Values.mongodb.persistence.accessModes }}
  accessModes:
    - {{ . }}
  {{- end }}
  claimRef:
     namespace: {{ .Release.Namespace }}
     name: {{ .Values.mongodb.persistence.existingClaim }}
  {{- with .Values.mongodb.volumeNodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4}}
  {{- end }}

