kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ .Values.mongodb.persistence.existingClaim }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.mongodb.persistence.storageClass | quote }}
spec:
  {{- range .Values.mongodb.persistence.accessModes }}
  accessModes:
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
